USE panaderia;


INSERT INTO USUARIOS(USERNAME, PASSWORD, ROL) VALUES
('cliente1', 'PASS123', 'CLIENTE'),
('cliente2', 'PASS123', 'CLIENTE'),
('empleado1', 'PASS123', 'EMPLEADO');


SELECT * FROM USUARIOS;


INSERT INTO CLIENTES(ID_USUARIO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ESTADO, CALLE, NUMERO, COLONIA) VALUES
(4, 'CARLOS', 'SANCHEZ', 'TORRES', '1995-06-10', 'ACTIVO', 'MORELOS', '500', 'CENTRO'),
(5, 'ANA', 'RIVERA', 'MARTINEZ', '1998-03-15', 'ACTIVO', 'HIDALGO', '800', 'VILLAS');

-- Verificar clientes
SELECT * FROM CLIENTES;


INSERT INTO TELEFONOS(ID_USUARIO, ETIQUETA, NUMERO) VALUES
(1, 'CELULAR', '6451234567'),
(1, 'CASA', '6454567890'),
(2, 'CELULAR', '6459876543'),
(4, 'CELULAR', '6451111111'),
(5, 'CELULAR', '6452222222');


SELECT * FROM TELEFONOS;


INSERT INTO PRODUCTOS(NOMBRE, TIPO, DESCRIPCION, PRECIO, DISPONIBLE) VALUES
('PAN BLANCO', 'SALADO', 'Pan blanco tradicional', 15.00, 1),
('DONAS CHOCOLATE', 'DULCE', 'Donas cubiertas de chocolate', 20.00, 1),
('PAN INTEGRAL', 'INTEGRAL', 'Pan integral saludable', 18.00, 1),
('CROISSANT', 'DULCE', 'Croissant danes crujiente', 25.00, 1),
('PIZZA SALADA', 'SALADO', 'Pizza con queso y jamon', 35.00, 1),
('GALLETAS AVENA', 'INTEGRAL', 'Galletas integrales de avena', 12.00, 1),
('PASTEL CHOCOLATE', 'DULCE', 'Pastel casero de chocolate', 45.00, 1),
('PAN AJO', 'SALADO', 'Pan tostado con ajo y mantequilla', 22.00, 1);


SELECT ID_PRODUCTO, NOMBRE, DISPONIBLE FROM PRODUCTOS;



INSERT INTO CUPONES(PORCENTAJE_DESCUENTO, FECHA_INICIO, FECHA_FIN, VIGENCIA, NUMERO_USOS) VALUES
(10.00, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1, 0),
(15.00, NOW(), DATE_ADD(NOW(), INTERVAL 15 DAY), 1, 0);


SELECT * FROM CUPONES;


SELECT 'USUARIOS:' as seccion;
SELECT COUNT(*) as total FROM USUARIOS;

SELECT 'CLIENTES:' as seccion;
SELECT COUNT(*) as total FROM CLIENTES;
SELECT ID_USUARIO, NOMBRES, APELLIDO_PATERNO FROM CLIENTES;

SELECT 'TELEFONOS:' as seccion;
SELECT COUNT(*) as total FROM TELEFONOS;

SELECT 'PRODUCTOS:' as seccion;
SELECT COUNT(*) as total FROM PRODUCTOS;
SELECT ID_PRODUCTO, NOMBRE, DISPONIBLE FROM PRODUCTOS;

SELECT 'CUPONES:' as seccion;
SELECT COUNT(*) as total FROM CUPONES;
















