DROP DATABASE IF EXISTS panaderia;
CREATE DATABASE panaderia;
USE panaderia;


-- TABLA USUARIOS 
CREATE TABLE USUARIOS (
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT, 
USERNAME VARCHAR(100) NOT NULL UNIQUE, -- NOMBRE DE USUARIO UNICO 
CONTRASEÑA VARCHAR(100) NOT NULL,
ROL ENUM('CLIENTE', 'EMPLEADO')NOT NULL
);
-- TABLA CLIENTES
CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRES VARCHAR(100) NOT NULL,
APELLIDO_PATERNO VARCHAR(100) NOT NULL,
APELLIDO_MATERNO VARCHAR(100) NOT NULL,
CALLE VARCHAR(100) NULL,
NUMERO VARCHAR(10) NULL,
COLONIA VARCHAR(100) NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ID_USUARIO INT UNIQUE,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);


-- TABLA TELEFONOS
CREATE TABLE TELEFONOS (
    ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ETIQUETA VARCHAR(20) NOT NULL, 
    NUMERO VARCHAR(10) NOT NULL,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

-- TABLA PEDIDOS
CREATE TABLE PEDIDOS(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NULL , -- Permite null para pedidos Express sin registro
    NUM_PEDIDO INT NOT NULL UNIQUE, -- NUMERO DE PEDIDO UNICO 
    ESTADO ENUM('PENDIENTE', 'EN PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO') NOT NULL DEFAULT 'PENDIENTE',
    FECHA_REGISTRO DATE NOT NULL,
    FECHA_ENTREGA DATE NULL,
    TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
); 

-- TABLA PEDIDOS_EXPRESS
CREATE TABLE PEDIDOS_EXPRESS(
    ID_PEDIDO INT PRIMARY KEY,
    FOLIO VARCHAR(20) NOT NULL,
    PIN VARCHAR (255), -- Longitud para hash encriptado
    TIEMPO_LIMITE DATETIME NOT NULL,
    TIEMPO_RECOLECCION DATETIME NULL, 
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- TABLA CUPONES
CREATE TABLE CUPONES(
    ID_CUPON INT PRIMARY KEY AUTO_INCREMENT,
    PORCENTAJE_DESCUENTO DECIMAL(5,2) NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NULL,
    NUMERO_USOS INT DEFAULT 0 -- Atributo para conteo 
);
-- TABLA PEDIDO PROGRAMADO
CREATE TABLE PEDIDOS_PROGRAMADOS(
ID_PEDIDO INT PRIMARY KEY,
ID_CUPON INT NULL,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
FOREIGN KEY(ID_CUPON) REFERENCES CUPONES(ID_CUPON)
);

-- TABLA PAGOS
CREATE TABLE PAGOS(
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL UNIQUE,
    METODO_PAGO ENUM('EFECTIVO', 'TARJETA') NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);


-- TABLA PRODUCTOS
CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO ENUM('DULCE', 'SALADO', 'INTEGRAL') NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PRECIO DECIMAL (10,2) NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL DEFAULT TRUE 
);

-- TABLA INGREDIENTES
CREATE TABLE INGREDIENTES(
    ID_INGREDIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

-- TABLA PRODUCTO_INGREDIENTES
CREATE TABLE PRODUCTO_INGREDIENTES(
    ID_PRODUCTO INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,
    PRIMARY KEY (ID_PRODUCTO, ID_INGREDIENTE),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID_INGREDIENTE)
);

-- TABLA DETALLE_PEDIDOS
CREATE TABLE DETALLE_PEDIDOS(
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL, 
    PRECIO_VENTA DECIMAL(10,2) NOT NULL, 
    SUBTOTAL DECIMAL(10,2), -- calculado en java
    NOTAS TEXT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);


-- TABLA HISTORIAL PEDIDOS para reportes 
CREATE TABLE HISTORIAL_PEDIDOS(
    ID_HISTORIAL INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_USUARIO INT NOT NULL ,
    ESTADO ENUM('PENDIENTE', 'EN PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO'),
    FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

INSERT INTO USUARIOS(USERNAME, CONTRASEÑA,ROL) VALUES
('JUANITO','PASS123','CLIENTE'),
('MARIA.M','CONTRASEGURA','CLIENTE'),
('PEPE.PECAS','ABC123','CLIENTE')
;

INSERT INTO CLIENTES(NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,CALLE,NUMERO,COLONIA,FECHA_NACIMIENTO,ID_USUARIO ) VALUES
('JUAN','PEREZ','GONZALES','CALIFORNIA','1325','CENTRO','2001-05-12',1),
('MARIA','MONTES','LOPEZ','JESUS GARCIA','255','VILLAS DEL NAINARI','2003-02-02',2),
('PEPE','PECAS','LOPEZ','6 DE ABRIL','897','CENTRO','2000-08-20',3)
;

SELECT *
FROM USUARIOS;
