DROP DATABASE IF EXISTS panaderia;
CREATE DATABASE panaderia;
USE panaderia;

-- TABLA USUARIOS 
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL, 
    ROL VARCHAR(20) NOT NULL 
);

-- TABLA CLIENTES
CREATE TABLE CLIENTES (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    -- Edad se removió para calcularla en java en la consulta con TIMESTAMPDIFF
    ESTADO VARCHAR(20) NOT NULL,
    CALLE VARCHAR(100) NULL,
    NUMERO VARCHAR(10) NULL,
    COLONIA VARCHAR(100) NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- TABLA TELEFONOS
CREATE TABLE TELEFONOS (
    ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ETIQUETA VARCHAR(20) NOT NULL, 
    NUMERO VARCHAR(13) NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);

-- TABLA CUPONES
CREATE TABLE CUPONES(
    ID_CUPON INT PRIMARY KEY AUTO_INCREMENT,
    PORCENTAJE_DESCUENTO DECIMAL(5,2) NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NULL,
    VIGENCIA BOOLEAN NOT NULL DEFAULT TRUE,
    NUMERO_USOS INT DEFAULT 0 -- Atributo para conteo 
);

-- TABLA PRODUCTOS
CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO ENUM('DULCE', 'SALADO', 'INTEGRAL') NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL DEFAULT TRUE 
);


-- TABLA PEDIDOS
CREATE TABLE PEDIDOS(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NULL, -- Permite null para pedidos Express sin registro
    NUM_PEDIDO INT UNIQUE NOT NULL,
    ESTADO ENUM('PENDIENTE', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO') NOT NULL DEFAULT 'PENDIENTE',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ENTREGA DATETIME NULL,
    TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
); 

-- TABLA PEDIDOS_PROGRAMADOS 
CREATE TABLE PEDIDOS_PROGRAMADOS(
    ID_PEDIDO INT PRIMARY KEY,
    ID_CUPON INT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_CUPON) REFERENCES CUPONES(ID_CUPON)
);

-- TABLA PEDIDOS_EXPRESS 
CREATE TABLE PEDIDOS_EXPRESS(
    ID_PEDIDO INT PRIMARY KEY,
    FOLIO VARCHAR(20) UNIQUE NOT NULL,
    PIN VARCHAR(255) NOT NULL, -- el PIN debe de ser de 8 pero por el encriptado lo dejé en 255
    TIEMPO_LIMITE DATETIME NOT NULL,
    TIEMPO_RECOLECCION DATETIME NULL, 
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- TABLA DETALLE_PEDIDOS
CREATE TABLE DETALLE_PEDIDOS(
    ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL, 
    PRECIO DECIMAL(10,2) NOT NULL, 
    SUBTOTAL DECIMAL(10,2), -- calculado en java
    NOTAS TEXT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- TABLA PAGOS
CREATE TABLE PAGOS(
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT UNIQUE NOT NULL, 
    METODO_PAGO ENUM('EFECTIVO', 'TARJETA') NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- TABLA HISTORIAL PEDIDOS para reportes 
CREATE TABLE HISTORIAL_PEDIDOS(
    ID_HISTORIAL INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ESTADO ENUM('PENDIENTE', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO'),
    FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- INSERTS DE PRUEBA
INSERT INTO USUARIOS(USERNAME, PASSWORD, ROL) VALUES
('JUANITO', 'PASS123', 'CLIENTE'),
('MARIA.M', 'CONTRASEGURA', 'CLIENTE'),
('PEPE.PECAS', 'ABC123', 'CLIENTE');

INSERT INTO CLIENTES(ID_USUARIO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ESTADO, CALLE, NUMERO, COLONIA) VALUES
(1, 'JUAN', 'PEREZ', 'GONZALES', '2001-05-12', 'ACTIVO', 'CALIFORNIA', '1325', 'CENTRO'),
(2, 'MARIA', 'MONTES', 'LOPEZ', '2003-02-02', 'ACTIVO', 'JESUS GARCIA', '255', 'VILLAS DEL NAINARI'),
(3, 'PEPE', 'PECAS', 'LOPEZ', '2000-08-20', 'ACTIVO', '6 DE ABRIL', '897', 'CENTRO');
