DROP DATABASE IF EXISTS panaderia; -- para eliminarla si ya hay una creada
CREATE DATABASE panaderia; -- creamos la base de datos
USE panaderia; -- la seleccionamos para poder utilizarla 


-- TABLA CLIENTES 

CREATE TABLE CLIENTES (
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRES VARCHAR(100) NOT NULL,
APELLIDO_PATERNO VARCHAR(100) NOT NULL,
APELLIDO_MATERNO VARCHAR(100) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT GENERATED ALWAYS AS(TIMESTAMPDIFF(YEAR,FECHA_NACIMIENTO,CURDATE())) STORED,
CALLE VARCHAR(100) NULL,
NUMERO VARCHAR(10) NULL,
COLONIA VARCHAR(100) NULL
);

-- TABLA TELEFONOS 
CREATE TABLE TELEFONOS (
ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
ETIQUETA ENUM('CASA', 'TRABAJO'),
NUMERO VARCHAR(10) NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

-- TABLA CUPONES
CREATE TABLE CUPONES(
ID_CUPON INT PRIMARY KEY AUTO_INCREMENT,
PORCENTAJE_DESCUENTO DECIMAL(5,2) NULL,
FECHA_INICIO DATETIME NOT NULL,
FECHA_FIN DATETIME NULL,
NUMERO_USOS INT DEFAULT 0
);

-- TABLA PRODUCTOS
CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
TIPO ENUM('DULCE', 'SALADO', 'INTEGRAL') NOT NULL,
DESCRIPCION TEXT NOT NULL,
PRECIO DECIMAL (10,2) NOT NULL,
DISPONIBLE BOOLEAN NOT NULL
);

-- TABLA INGREDIENTES
CREATE TABLE INGREDIENTES(
ID_INGREDIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100)
);

-- TABLA PRODUCTO_INGREDIENTES
CREATE TABLE PRODUCTO_INGREDIENTES(
ID_PRODUCTO INT NOT NULL,
ID_INGREDIENTE INT NOT NULL,
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID_INGREDIENTE)
);

-- TABLA PEDIDOS
CREATE TABLE PEDIDOS(
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NULL,
ID_CUPON INT NULL,
NUM_PEDIDO INT NOT NULL,
ESTADO ENUM('PENDIENTE', 'EN PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO') NOT NULL DEFAULT 'PENDIENTE',
TOTAL DECIMAL(10,2) NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY (ID_CUPON) REFERENCES CUPONES (ID_CUPON)
); 

-- TABLA DETALLE_PEDIDOS
CREATE TABLE DETALLE_PEDIDOS(
ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
NOTAS TEXT NULL,
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODCUTO)
);

-- TABLA PEDIDOS_EXPRESS
CREATE TABLE PEDIDOS_EXPRESS(
ID_PEDIDO INT PRIMARY KEY,
FOLIO VARCHAR(20) NOT NULL,
PIN VARCHAR (255),
TIEMPO_LIMITE DATETIME NOT NULL,
TIEMPO_RECOLECCION DATETIME NOT NULL,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- TABLA PAGOS
CREATE TABLE PAGOS(
ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
METODO_PAGO ENUM('EFECTIVO', 'TARJETA')NOT NULL,
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- TABLA HISTORIAL PEDIDOS
CREATE TABLE HISTORIAL_PEDIDOS(
ID_HISTORIAL INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ESTADO ENUM('PENDIENTE', 'EN PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO RECLAMADO'),
FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);
