-- PANADERÍA
-- Bases de Datos Avanzadas 
-- Integrantes: Kevin A. Mendoza, Cristian E. Devora, Jazmin Baldenegro


DROP DATABASE IF EXISTS panaderia;
CREATE DATABASE panaderia;
USE panaderia;


-- TABLAS


CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,     -- encriptado SHA-256
    ROL VARCHAR(20) NOT NULL            -- 'CLIENTE' o 'EMPLEADO'
);


CREATE TABLE CLIENTES (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    CALLE VARCHAR(100) NULL, 
    NUMERO VARCHAR(10) NULL,
    COLONIA VARCHAR(100) NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);


CREATE TABLE TELEFONOS (
    ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ETIQUETA VARCHAR(20) NOT NULL,      
    NUMERO VARCHAR(13) NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
    );


CREATE TABLE CUPONES (
    ID_CUPON INT PRIMARY KEY AUTO_INCREMENT,
    PORCENTAJE_DESCUENTO DECIMAL(5,2) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NULL,
    VIGENCIA BOOLEAN NOT NULL DEFAULT TRUE,
    NUMERO_USOS INT DEFAULT 0,
    MAXIMO_USOS INT DEFAULT NULL        
);


CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO ENUM('DULCE', 'SALADO', 'INTEGRAL') NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL DEFAULT TRUE,
    IMAGEN VARCHAR(100) NULL DEFAULT NULL    -- nombre del archivo en /com/imagenes/
);


CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NULL,                -- NULL para pedidos Express sin registro
    NUM_PEDIDO INT UNIQUE NOT NULL,
    ESTADO ENUM('PENDIENTE', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO_ENTREGADO') NOT NULL DEFAULT 'PENDIENTE',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ENTREGA DATETIME NULL,
    TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);


CREATE TABLE PEDIDOS_PROGRAMADOS (
    ID_PEDIDO INT PRIMARY KEY,
    ID_CUPON INT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_CUPON) REFERENCES CUPONES(ID_CUPON)
);


CREATE TABLE PEDIDOS_EXPRESS (
    ID_PEDIDO INT PRIMARY KEY,
    FOLIO VARCHAR(20) UNIQUE NOT NULL,
    PIN VARCHAR(255) NOT NULL,          -- PIN de 8 dígitos encriptado 
    TIEMPO_LIMITE DATETIME NULL,        -- Se asigna cuando el pedido pasa a LISTO con el trigger TRG_TIEMPO_LIMITE_EXPRESS
    TIEMPO_RECOLECCION DATETIME NULL,  
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);


CREATE TABLE DETALLE_PEDIDOS (
    ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,      
    SUBTOTAL DECIMAL(10,2),             
    NOTAS TEXT NULL,                     
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);


CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT UNIQUE NOT NULL,      -- Un pago por pedido
    METODO_PAGO ENUM('EFECTIVO', 'TARJETA') NOT NULL,
    FECHA_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MONTO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);


CREATE TABLE HISTORIAL_PEDIDOS (
    ID_HISTORIAL INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ESTADO ENUM('PENDIENTE', 'LISTO', 'ENTREGADO', 'CANCELADO', 'NO_ENTREGADO') NOT NULL,
    FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);



-- TRIGGERS

-- Cuando un pedido cambia a LISTO, se pone el tiempo límite en 20 min para pedidos express
DELIMITER $$
CREATE TRIGGER TRG_TIEMPO_LIMITE_EXPRESS
AFTER UPDATE ON PEDIDOS
FOR EACH ROW
BEGIN
    IF NEW.ESTADO = 'LISTO' AND OLD.ESTADO != 'LISTO' THEN
        IF EXISTS (SELECT 1 FROM PEDIDOS_EXPRESS WHERE ID_PEDIDO = NEW.ID_PEDIDO) THEN
            UPDATE PEDIDOS_EXPRESS
            SET TIEMPO_LIMITE = DATE_ADD(NOW(), INTERVAL 20 MINUTE),
                TIEMPO_RECOLECCION = NULL
            WHERE ID_PEDIDO = NEW.ID_PEDIDO;
        END IF;
    END IF;
END $$
DELIMITER ;


-- Registrar automáticamente cada cambio de estado en el historial
DELIMITER $$
CREATE TRIGGER TRG_REGISTRAR_HISTORIAL
AFTER UPDATE ON PEDIDOS
FOR EACH ROW
BEGIN
    IF NEW.ESTADO != OLD.ESTADO THEN
        INSERT INTO HISTORIAL_PEDIDOS (ID_PEDIDO, ESTADO, FECHA_HORA)
        VALUES (NEW.ID_PEDIDO, NEW.ESTADO, NOW());
    END IF;
END $$
DELIMITER ;


-- Registrar estado inicial PENDIENTE en historial al crear pedido
DELIMITER $$
CREATE TRIGGER TRG_HISTORIAL_PEDIDO_NUEVO
AFTER INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
    INSERT INTO HISTORIAL_PEDIDOS (ID_PEDIDO, ESTADO, FECHA_HORA)
    VALUES (NEW.ID_PEDIDO, NEW.ESTADO, NOW());
END $$
DELIMITER ;



-- Procedimientos

-- SP para validar un cupón antes de aplicarlo
DELIMITER $$
CREATE PROCEDURE SP_VALIDAR_CUPON(
    IN P_ID_CUPON INT,
    OUT P_VALIDO BOOLEAN,
    OUT P_PORCENTAJE DECIMAL(5,2),
    OUT P_MENSAJE VARCHAR(255)
)
BEGIN
    DECLARE V_VIGENCIA BOOLEAN;
    DECLARE V_FECHA_INICIO DATETIME;
    DECLARE V_FECHA_FIN DATETIME;
    DECLARE V_NUMERO_USOS INT;
    DECLARE V_MAXIMO_USOS INT;
    DECLARE V_PORCENTAJE DECIMAL(5,2);

    -- Busca el cupón
    SELECT VIGENCIA, FECHA_INICIO, FECHA_FIN, NUMERO_USOS, MAXIMO_USOS, PORCENTAJE_DESCUENTO
    INTO V_VIGENCIA, V_FECHA_INICIO, V_FECHA_FIN, V_NUMERO_USOS, V_MAXIMO_USOS, V_PORCENTAJE
    FROM CUPONES
    WHERE ID_CUPON = P_ID_CUPON;

    -- Si no existe el cupón
    IF V_VIGENCIA IS NULL THEN
        SET P_VALIDO = FALSE;
        SET P_PORCENTAJE = 0;
        SET P_MENSAJE = 'El cupón no existe';

    -- Si está marcado como no vigente
    ELSEIF V_VIGENCIA = FALSE THEN
        SET P_VALIDO = FALSE;
        SET P_PORCENTAJE = 0;
        SET P_MENSAJE = 'El cupón ya no está vigente';

    -- Si aún no inicia su vigencia
    ELSEIF NOW() < V_FECHA_INICIO THEN
        SET P_VALIDO = FALSE;
        SET P_PORCENTAJE = 0;
        SET P_MENSAJE = 'El cupón aún no está activo';

    -- Si ya expiró
    ELSEIF V_FECHA_FIN IS NOT NULL AND NOW() > V_FECHA_FIN THEN
        SET P_VALIDO = FALSE;
        SET P_PORCENTAJE = 0;
        SET P_MENSAJE = 'El cupón ha expirado';

    -- Si excedió el máximo de usos
    ELSEIF V_MAXIMO_USOS IS NOT NULL AND V_NUMERO_USOS >= V_MAXIMO_USOS THEN
        SET P_VALIDO = FALSE;
        SET P_PORCENTAJE = 0;
        SET P_MENSAJE = 'El cupón ha alcanzado su límite de usos';

    -- Cupón válido
    ELSE
        SET P_VALIDO = TRUE;
        SET P_PORCENTAJE = V_PORCENTAJE;
        SET P_MENSAJE = 'Cupón válido';
    END IF;
END $$
DELIMITER ;



-- Inserts de prueba

INSERT INTO USUARIOS(USERNAME, PASSWORD, ROL) VALUES
('juanito',     SHA2('cliente123', 256), 'CLIENTE'),
('maria.m',     SHA2('cliente456', 256), 'CLIENTE'),
('pepe.pecas',  SHA2('cliente789', 256), 'CLIENTE'),
('carlos.s',    SHA2('cliente123', 256), 'CLIENTE'),
('ana.r',       SHA2('cliente456', 256), 'CLIENTE'),
('admin1',      SHA2('empleado123', 256), 'EMPLEADO');

-- CLIENTES
INSERT INTO CLIENTES(ID_USUARIO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ESTADO, CALLE, NUMERO, COLONIA) VALUES
(1, 'JUAN',   'PEREZ',   'GONZALES',  '2001-05-12', 'ACTIVO', 'CALIFORNIA',    '1325', 'CENTRO'),
(2, 'MARIA',  'MONTES',  'LOPEZ',     '2003-02-02', 'ACTIVO', 'JESUS GARCIA',  '255',  'VILLAS DEL NAINARI'),
(3, 'PEPE',   'PECAS',   'LOPEZ',     '2000-08-20', 'ACTIVO', '6 DE ABRIL',    '897',  'CENTRO'),
(4, 'CARLOS', 'SANCHEZ', 'TORRES',    '1995-06-10', 'ACTIVO', 'MORELOS',       '500',  'CENTRO'),
(5, 'ANA',    'RIVERA',  'MARTINEZ',  '1998-03-15', 'ACTIVO', 'HIDALGO',       '800',  'VILLAS');

-- TELEFONOS
INSERT INTO TELEFONOS(ID_USUARIO, ETIQUETA, NUMERO) VALUES
(1, 'CELULAR', '6451234567'),
(1, 'CASA',    '6454567890'),
(2, 'CELULAR', '6459876543'),
(3, 'CELULAR', '6451112233'),
(4, 'CELULAR', '6451111111'),
(4, 'TRABAJO', '6443334444'),
(5, 'CELULAR', '6452222222');

-- PRODUCTOS
INSERT INTO PRODUCTOS(NOMBRE, TIPO, DESCRIPCION, PRECIO, DISPONIBLE, IMAGEN) VALUES
('PAN BLANCO',       'SALADO',   'Pan blanco tradicional de masa suave',            15.00, TRUE,  'panblanco.jpg'),
('DONAS CHOCOLATE',  'DULCE',    'Donas cubiertas de chocolate con chispas',        20.00, TRUE,  'dona.jpg'),
('PAN INTEGRAL',     'INTEGRAL', 'Pan integral saludable con semillas',             18.00, TRUE,  'panintegral.jpg'),
('CROISSANT',        'DULCE',    'Croissant danés crujiente con mantequilla',       25.00, TRUE,  'croissant.jpg'),
('PIZZA SALADA',     'SALADO',   'Pizza artesanal con queso y jamón',               35.00, TRUE,  'pizzasalada.png'),
('GALLETAS AVENA',   'INTEGRAL', 'Galletas integrales de avena y miel',             12.00, TRUE,  'galletasavena.jpg'),
('PASTEL CHOCOLATE', 'DULCE',    'Pastel casero de chocolate con cobertura',        45.00, TRUE,  'pastelchocolate.jpg'),
('PAN DE AJO',       'SALADO',   'Pan tostado con ajo y mantequilla de hierbas',    22.00, TRUE,  'pandeajo.jpg'),
('ROLES DE CANELA',  'DULCE',    'Roles suaves con canela y glaseado',              28.00, TRUE,  'rolesdecanela.jpg'),
('PAN MULTIGRANO',   'INTEGRAL', 'Pan con mezcla de granos y cereales',             20.00, TRUE,  'panmultigrano.jpg'),
('EMPANADA JAMON',   'SALADO',   'Empanada rellena de jamón y queso',               30.00, FALSE, NULL);

-- CUPONES
INSERT INTO CUPONES(PORCENTAJE_DESCUENTO, FECHA_INICIO, FECHA_FIN, VIGENCIA, NUMERO_USOS, MAXIMO_USOS) VALUES
(10.00, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), TRUE,  0, 50),    -- 10% descuento, 50 usos máx
(15.00, NOW(), DATE_ADD(NOW(), INTERVAL 15 DAY), TRUE,  0, 20),    -- 15% descuento, 20 usos máx
(20.00, '2025-01-01', '2025-12-31',              FALSE, 10, 10),   -- Cupón expirado para probar validación
(5.00,  NOW(), DATE_ADD(NOW(), INTERVAL 60 DAY), TRUE,  0, NULL);  -- 5% descuento, usos ilimitados



-- pruebas

SELECT ID_USUARIO, USERNAME, ROL FROM USUARIOS;


SELECT c.ID_USUARIO, c.NOMBRES, c.APELLIDO_PATERNO, c.ESTADO
FROM CLIENTES c;


SELECT t.ID_USUARIO, t.ETIQUETA, t.NUMERO
FROM TELEFONOS t;


SELECT ID_PRODUCTO, NOMBRE, TIPO, PRECIO, DISPONIBLE FROM PRODUCTOS;


SELECT ID_CUPON, PORCENTAJE_DESCUENTO, VIGENCIA, NUMERO_USOS, MAXIMO_USOS FROM CUPONES;

-- Probar el procedimiento 
CALL SP_VALIDAR_CUPON(1, @valido, @porcentaje, @mensaje);
SELECT @valido AS cupon_valido, @porcentaje AS porcentaje, @mensaje AS mensaje;

CALL SP_VALIDAR_CUPON(3, @valido, @porcentaje, @mensaje);
SELECT @valido AS cupon_valido, @porcentaje AS porcentaje, @mensaje AS mensaje;

CALL SP_VALIDAR_CUPON(999, @valido, @porcentaje, @mensaje);
SELECT @valido AS cupon_valido, @porcentaje AS porcentaje, @mensaje AS mensaje;