USE panaderia;

-- SE ACTIVARA ANTES DE QUE EL REGISTRO SE GUARDE
DELIMITER **
CREATE TRIGGER  TRG_TIEMPOS_PEDIDOS_EXPRESS
BEFORE INSERT ON PEDIDOS_EXPRESS 
FOR EACH ROW
BEGIN
	SET NEW.TIEMPO_RECOLECCION = NOW(); -- SE LE ASIGNARA A LA FECHA DE RECOLECCION LA FECHA ACTUAL
    SET NEW.TIEMPO_LIMITE = DATE_ADD(NEW.TIEMPO_RECOLECCION,INTERVAL 20 MINUTE); -- DATE_ADD PARA AGREGAR TIEMPO A LA FECHA
								-- SI EL PEDIDO SE HACE A LAS 4:00 EL RESULTADO SERA 4:20
	
END **
DELIMITER ;


-- SI SE EXCEDE DE LOS 20 MINUTOS EL ESTADO DEL PEDIDO PASA A NO ENTREGADO

DELIMITER $$

CREATE TRIGGER TRG_ESTADO_PEDIDO
AFTER UPDATE ON PEDIDOS_EXPRESS
FOR EACH ROW
BEGIN
	IF NOW() > OLD.TIEMPO_LIMITE THEN
    UPDATE PEDIDOS
    SET ESTADO = 'NO RECLAMADO'
    WHERE ID_PEDIDO = OLD.ID_PEDIDO;
    END IF;
END $$

DELIMITER ;

-- store procedure para validar el cupon
DELIMITER ++

CREATE PROCEDURE SP_VALIDAR_CUPON(
IN ID_CUPON INT
)
BEGIN
	DECLARE V_C_FECHA_FIN DATETIME;
    SELECT FECHA_FIN
    INTO V_C_FECHA_FIN
    FROM CUPONES
    WHERE ID_CUPON = ID_CUPON;
    -- SI LA FECHA ACTUAL ES MAYOR A LA FECHA FIN DEL CUPON
    -- MOSTRARA EL MENSAJE QUE EL CUPON ESTÁ VENCIDO
    IF NOW() > V_C_FECHA_FIN THEN
    SET MESSAGE = 'El cupón está vencido';
    END IF;
END ++

DELIMITER ;


